### ISSUE TITLE
Add Logging

### ISSUE THREAD

**Issue by tomwendel** [AusLiebeZumCode/OctoPatch#18]
Wir brauchen für das Monitoring unbedingt eine Art logger. Console.Writeline kanns nicht sein ;)
Möglichkeiten:
- Ein spezifisches Framework (gerne NLog) einbinden
- Ein Interface basteln um einen Beliebigen Wrapper für das Framework unserer Wahl bauen
- Einen simplen Log-Delegaten einfügen

Meinungen?

**Comment by TheBlubb14** [comment]
Ich würde [Serilog](https://github.com/serilog/serilog) als Log-Framework vorschlagen ;)

**Comment by m4cx** [comment]
Serilog würde ich nur als Output konfigurieren. Ich würde mit den Microsoft.Extensions.Logging.Abstractions intern arbeiten. Dann kannst du Serilog dranflanschen. Beispiel kannst du hier sehen:

https://github.com/m4cx/kraken-wsapi-dotnet/blob/master/samples/Kraken.WebSockets.Sample/Program.cs

**Comment by tomwendel** [comment]
In wie weit muss dann unser Code Serilog kennen? Ich sehe die Abstraktion noch nicht

**Comment by m4cx** [comment]
Das sind die beiden entscheidenden Teile:
```csharp
// Erstelle den Serilog Logger - Sollte in der Program.cs oder ähnlicher Stelle passieren. Runtime-Umgebung halt. 
var logger = new LoggerConfiguration()
    .MinimumLevel.Verbose()
    .WriteTo.RollingFile("logs/kraken-websockets.log")
    .WriteTo.Console(restrictedToMinimumLevel: Serilog.Events.LogEventLevel.Information)
    .CreateLogger();

// LoggerFactory stammt aus Microsoft.Extensions.Logging Die LoggerFactory kümmert sich um die Erstellung der Logger Instanzen
 _ = new LoggerFactory() 
    .AddKrakenWebSockets() // Füge die LoggerFactory an eine Manager-Klasse an, oder reiche sie per DI weiter
    .AddSerilog(logger); // Füge den Serilog Logger an die LoggerFactory an
```

Alternativ können wir auch die Integration von serilog nutzen:
https://github.com/serilog/serilog-aspnetcore

Die wird beim Startup vom WebHost / der Runtime von OctoPatch initialisiert. In der weiteren Anwendung verwendest du den ILogger aus `Microsoft.Extensions.Logging.Abstractions`

**Comment by tomwendel** [comment]
Ah. der letzte Teil (ILogger abstracton) hat mir gefehlt

**Comment by m4cx** [comment]
Ich würde mir den ILogger aber im Gegensatz zum gegebenen Beispiel aber immer über die DI injecten lassen. Sonst hast du dort eine versteckte Abhängigkeit.

**Comment by TheBlubb14** [comment]
Super Idee dann https://www.nuget.org/packages/Microsoft.Extensions.Logging.Abstractions/ benutzen und intern mit `ILogger` arbeiten. Und im Startup mit https://github.com/serilog/serilog-aspnetcore den Logger einfügen

**Comment by m4cx** [comment]
@tomwendel 
Ich würd mir das Ticket dann nehmen wollen...

**Comment by tomwendel** [comment]
Dann viel Spaß damit :)

**Comment by m4cx** [comment]
#27

**Comment by tomwendel** [comment]
<3

**Comment by m4cx** [comment]
Fertig, oder?

**Comment by tomwendel** [comment]
ist doch gemergt

**Comment by TheBlubb14** [comment]
Das Issue ist noch offen, das meint er ^^
