### ISSUE TITLE
CI: Build action for NuGet Package

### ISSUE THREAD

**Issue by tomwendel** [AusLiebeZumCode/OctoPatch#6]
Das Tool muss ordentlich paketiert werden. Idealerweise per Git Action direkt zum NuGet Package

**Comment by TheBlubb14** [comment]
Ich würde dann das mal angehen. 
* Welche Projekte sollen als NuGet Paket verteilt werden? Nur `OctoPatch`, richtig?
* Soll automatisch die Version hochgezählt werden? Es gibt da eine interresante [Action ](https://github.com/anothrNick/github-tag-action)
* Für welche Projekte sollen die gebauten Dlls (Artifacts) in der jeweiligen Action Ausführung (Workflow Run) hochgeladen/gespeichert werden?

**Comment by tomwendel** [comment]
Aktuell brauchen wir wohl am ehesten OctoPatch, ja. Später evtl. Host. Oder Host wandert in OctoPatch? Wer weiß...
Versionierung ist eine wirklich gute Frage. Spannend wäre, wenn wir Major und Minor per Tag festlegen könnten? Und der Rest darf gerne automatisch hochzählen.

Würde Major als Contact Break sehen, Minor als kleines Update
